blog/urls.py
from django.contrib.auth.decorators import login_required, permission_required
from django.urls import path
from .views import (
    BlogPostHomeView,
    BlogPostDetailView,
    BlogPostCreateView,
    BlogPostUpdateView,
    BlogPostDeleteView,
    CategoryView,
    LikeView,
    CommentDeleteView,
    CommentEditView,
)

app_name = 'blog'

urlpatterns = [
    path('', BlogPostHomeView.as_view(), name='blogs'),
    path('create/', login_required(BlogPostCreateView.as_view()), name='create'),
    path('edit/<slug>/', login_required(BlogPostUpdateView.as_view()), name='update'),
    path('delete/<slug>/', login_required(BlogPostDeleteView.as_view()), name='delete'),
    path('<slug>/', BlogPostDetailView.as_view(), name='detail'),
    path('categories/<cat>/', CategoryView, name='category'),
    path('like/<slug>/', LikeView, name='like-post'),
    path('delete/comment/<int:pk>/', login_required(CommentDeleteView.as_view()), name='delete-comment'),
    path('edit/comment/<int:pk>/', login_required(CommentEditView.as_view()), name='edit-comment'),
]

main/urls.py
from django.contrib.auth.decorators import login_required, permission_required
from django.urls import path
from .views import (
    HomeView,
    ShowProfilePageView,
    EditProfilePageView,
)

app_name = 'main'

urlpatterns = [
    path('', HomeView.as_view(), name='index'),
    path('<slug>/accounts/profile/', ShowProfilePageView.as_view(), name='user-profile'),
    path('<slug>/accounts/edit/profile/', login_required(EditProfilePageView.as_view()), name='edit-profile'),
]

oduduwa/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('posts/', include('blog.urls', namespace='blog')),
    path('accounts/', include('allauth.urls')),
    path('search/', include("searches.urls", namespace='searches')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

searches/urls.py
from django.urls import path

from .views import (
    SearchBlogView,
)

app_name = 'searches'

urlpatterns = [
    path('', SearchBlogView.as_view(), name='blog-query'),
]

templates/snippets/admissions_area.html
<div data-scroll-index='1' class="admission_area">
    <div class="admission_inner">
        <div class="container">
            <div class="row justify-content-end">
                <div class="col-lg-7">
                    <div class="admission_form">
                        <h3>Apply for Admission</h3>
                        <form action="#">
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="single_input">
                                        <input type="text" placeholder="First Name" >
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="single_input">
                                        <input type="text" placeholder="Last Name" >
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="single_input">
                                        <input type="text" placeholder="Phone Number" >
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="single_input">
                                        <input type="text" placeholder="Email Address" >
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="single_input">
                                        <textarea cols="30" placeholder="Write an Application" rows="10"></textarea>
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="apply_btn">
                                        <button class="boxed-btn3" type="submit">Apply Now</button>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

templates/snippets/blog-search.html
<div class="col-lg-4">
    <div class="blog_right_sidebar">
        <aside class="single_sidebar_widget search_widget">
            <form action="{% url 'searches:blog-query' %}">
                <div class="form-group">
                    <div class="input-group mb-3">
                        <input name="q" type="text" class="form-control" placeholder='Search Keyword'
                            onfocus="this.placeholder = ''"
                            onblur="this.placeholder = 'Search Keyword'">
                        <div class="input-group-append">
                            <button class="btn" type="submit"><i class="ti-search"></i></button>
                        </div>
                    </div>
                </div>
                <button class="button rounded-0 primary-bg text-white w-100 btn_1 boxed-btn"
                    type="submit">Search</button>
            </form>
        </aside>

        {% include "snippets/category.html" %}

    </div>
</div>

templates/snippets/category.html
<aside class="single_sidebar_widget post_category_widget">
    <h4 class="widget_title">Category</h4>
    <ul class="list cat-list">
        <li>
            <a href="/posts/categories/announcement" class="d-flex">
                <p>Announcement</p>
            </a>
        </li>
        <li>
            <a href="/posts/categories/school-news" class="d-flex">
                <p>School News</p>
            </a>
        </li>
    </ul>
</aside>

templates/snippets/footer.html
<footer class="footer">
    <!-- <div class="footer_top">
        <div class="container">
            <div class="row">
                <div class="col-xl-3 col-md-6 col-lg-3">
                    <div class="footer_widget">
                        <h3 class="footer_title">
                            About Us
                        </h3>
                        <ul>
                            <li><a href="#">Online Learning</a></li>
                            <li><a href="#">About Us</a></li>
                            <li><a href="#">Careers</a></li>
                            <li><a href="#">Press Center</a></li>
                            <li><a href="#">Become an Instructor</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-xl-3 col-md-6 col-lg-3">
                    <div class="footer_widget">
                        <h3 class="footer_title">
                            Campus
                        </h3>
                        <ul>
                            <li><a href="#">Our Plans</a></li>
                            <li><a href="#">Free Trial</a></li>
                            <li><a href="#">Academic Solutions</a></li>
                            <li><a href="#">Business Solutions</a></li>
                            <li><a href="#">Government Solutions</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-xl-3 col-md-6 col-lg-3">
                    <div class="footer_widget">
                        <h3 class="footer_title">
                            Study
                        </h3>
                        <ul>
                            <li><a href="#">Admissions Policy</a></li>
                            <li><a href="#">Getting Started</a></li>
                            <li><a href="#">Visa Information</a></li>
                            <li><a href="#">Tuition Calculator</a></li>
                            <li><a href="#">Request Information</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-xl-3 col-md-6 col-lg-3">
                    <div class="footer_widget">
                        <h3 class="footer_title">
                            Support
                        </h3>
                        <ul>
                            <li><a href="#">Support</a></li>
                            <li><a href="#">Contact Us</a></li>
                            <li><a href="#">System Requirements</a></li>
                            <li><a href="#">Register Activation Key</a></li>
                            <li><a href="#">Site feedback</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div> -->
    <div class="copy-right_text">
        <div class="container">
            <div class="footer_border"></div>
            <div class="row">
                <div class="col-xl-12">
                    <p class="copy_right text-center">
                        <p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> Oduduwa Junior & Secondary School
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
                    </p>
                </div>
            </div>
        </div>
    </div>
</footer>

templates/snippets/latest_courses_area.html
<div class="latest_coures_area">
    <div class="latest_coures_inner">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                    <div class="coures_info">
                        <div class="section_title white_text">
                            <h3>Latest Courses</h3>
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod <br> tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim <br> veniam, quis nostrud exercitation.</p>
                        </div>
                        <div class="coures_wrap d-flex">
                            <div class="single_wrap">
                                <div class="icon">
                                    <i class="flaticon-lab"></i>
                                </div>
                                <h4>Bachelor of <br>
                                    Graphic Design</h4>
                                    <p>Lorem ipsum dolor sit amet, sectetur adipiscing elit, sed do eiusmod tpor incididunt ut piscing vcs.</p>
                                    <a href="#" class="boxed-btn5">Apply NOw</a>
                            </div>
                            <div class="single_wrap">
                                <div class="icon">
                                    <i class="flaticon-lab"></i>
                                </div>
                                <h4>Bachelor of <br>
                                    Graphic Design</h4>
                                    <p>Lorem ipsum dolor sit amet, sectetur adipiscing elit, sed do eiusmod tpor incididunt ut piscing vcs.</p>
                                    <a href="#" class="boxed-btn5">Apply NOw</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

templates/snippets/navbar.html
<header>
    <div class="header-area ">
        <div class="header-top_area">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="header_top_wrap d-flex justify-content-between align-items-center">
                            <div class="text_wrap">
                                <!-- <p><span>+880166 253 232</span> <span>info@domain.com</span></p> -->
                            </div>
                            <div class="text_wrap">
                                <p>
                                {% if user.is_authenticated %}
                                    <a href="{% url 'main:user-profile' slug=user.userprofile.slug %}"><i class="ti-user"></i>  {{ request.user }}</a> <a href="{% url 'account_logout' %}">Logout</a>
                                {% else %}
                                    <a href="{% url 'account_login' %}"> <i class="ti-user"></i>  Login </a><a href="{% url 'account_signup' %}">Register</a>
                                {% endif %}
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div id="sticky-header" class="main-header-area">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="header_wrap d-flex justify-content-between align-items-center">
                            <div class="header_left">
                                <div class="logo">
                                    <a href="/">
                                        <!-- <img src="img/logo.png" alt=""> -->
                                        <h2>Oduduwa</h2>
                                        <h3 class="ml-3">Jun & Sec</h3>
                                    </a>
                                </div>
                            </div>
                            <div class="header_right d-flex align-items-center">
                                <div class="main-menu  d-none d-lg-block">
                                    <nav>
                                        <ul id="navigation">
                                            <li><a href="/">Home</a></li>
                                            
                                            {% if user.is_authenticated %}
                                            <li><a href="#">blog <i class="ti-angle-down"></i></a>
                                                <ul class="submenu">
                                                    <li><a href="{% url 'blog:blogs' %}">Posts</a></li>
                                                    <li><a href="{% url 'blog:create' %}">Create Post</a></li>
                                                </ul>
                                            </li>
                                            {% else %}
                                            <li><a href="{% url 'blog:blogs' %}">Posts</a></li>
                                            {% endif %}
                                                
                                            <li><a href="#">blank </a>
                                                <!-- <ul class="submenu">
                                                    <li><a href="Event.html">Event</a></li>
                                                    <li><a href="event_details.html">Event Details</a></li>
                                                    <li><a href="Admissions.html">Admissions</a></li>
                                                    <li><a href="elements.html">elements</a></li>
                                                </ul> -->
                                            </li>
                                            <li><a href="#">blank </a></li>
                                        </ul>
                                    </nav>
                                </div>
                                <!-- <div class="Appointment">
                                    <div class="book_btn d-none d-lg-block">
                                        <a data-scroll-nav='1' href="#">Apply NOw</a>
                                    </div>
                                </div> -->
                            </div>
                        </div>
                    </div>
                    <div class="col-12">
                        <div class="mobile_menu d-block d-lg-none" style="margin-top: -20px;"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</header>

templates/snippets/pagination.html
<nav class="blog-pagination justify-content-center d-flex">
    <ul class="pagination">
        
        {% if page_obj.has_previous %}
        <li class="page-item">
            <a href="?page={{ page_obj.previous_page_number }}" class="page-link" aria-label="Previous">
                <i class="ti-angle-left"></i>
            </a>
        </li>
        {% endif %}

        <li class="page-item active">
            <a href="?page={{ page_obj.number }}" class="page-link">{{ page_obj.number }}</a>
        </li>
        <li class="page-item disabled">
            <span class="page-link">/{{ page_obj.paginator.num_pages }}</span>
        </li>

        {% if page_obj.has_next %}
        <li class="page-item">
            <a href="?page={{ page_obj.next_page_number }}" class="page-link" aria-label="Next">
                <i class="ti-angle-right"></i>
            </a>
        </li>
        {% endif %}

    </ul>
</nav>

templates/snippets/pop_prog_area.html
<div class="popular_program_area section__padding">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="section_title text-center">
                    <h3>Popular Program</h3>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <nav class="custom_tabs text-center">
                    <div class="nav" id="nav-tab" role="tablist">
                        <a class="nav-item nav-link active" id="nav-home-tab" data-toggle="tab" href="#nav-home" role="tab" aria-controls="nav-home" aria-selected="true">Graduate                                </a>
                        <a class="nav-item nav-link" id="nav-profile-tab" data-toggle="tab" href="#nav-profile" role="tab" aria-controls="nav-profile" aria-selected="false">Postgraduate </a>
                        <a class="nav-item nav-link" id="nav-contact-tab" data-toggle="tab" href="#nav-contact" role="tab" aria-controls="nav-contact" aria-selected="false">PHD Scholarships</a>
                        <a class="nav-item nav-link" id="nav-contact-tab" data-toggle="tab" href="#nav-contact2" role="tab" aria-controls="nav-contact" aria-selected="false">Training</a>
                    </div>
                </nav>
            </div>
        </div>
        <div class="tab-content" id="nav-tabContent">
            <div class="tab-pane fade show active" id="nav-home" role="tabpanel" aria-labelledby="nav-home-tab">
                <div class="row">
                    <div class="col-lg-4 col-md-6">
                        <div class="single__program">
                            <div class="program_thumb">
                                <img src="img/program/1.png" alt="">
                            </div>
                            <div class="program__content">
                                <span>Agriculture</span>
                                <h4>Chemical engneering</h4>
                                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut</p>
                                <a href="#" class="boxed-btn5">Apply NOw</a>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-6">
                        <div class="single__program">
                            <div class="program_thumb">
                                <img src="img/program/2.png" alt="">
                            </div>
                            <div class="program__content">
                                <span>Agriculture</span>
                                <h4>Mechanical engneering</h4>
                                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut</p>
                                <a href="#" class="boxed-btn5">Apply NOw</a>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-6">
                        <div class="single__program">
                            <div class="program_thumb">
                                <img src="img/program/3.png" alt="">
                            </div>
                            <div class="program__content">
                                <span>Agriculture</span>
                                <h4>Bio engneering</h4>
                                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut</p>
                                <a href="#" class="boxed-btn5">Apply NOw</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="tab-pane fade" id="nav-profile" role="tabpanel" aria-labelledby="nav-profile-tab">
                            <div class="row">
                        <div class="col-lg-4 col-md-6">
                            <div class="single__program">
                                <div class="program_thumb">
                                    <img src="img/program/1.png" alt="">
                                </div>
                                <div class="program__content">
                                    <span>Agriculture</span>
                                    <h4>Chemical engneering</h4>
                                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut</p>
                                    <a href="#" class="boxed-btn5">Apply NOw</a>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-4 col-md-6">
                            <div class="single__program">
                                <div class="program_thumb">
                                    <img src="img/program/3.png" alt="">
                                </div>
                                <div class="program__content">
                                    <span>Agriculture</span>
                                    <h4>Mechanical engneering</h4>
                                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut</p>
                                    <a href="#" class="boxed-btn5">Apply NOw</a>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-4 col-md-6">
                            <div class="single__program">
                                <div class="program_thumb">
                                    <img src="img/program/2.png" alt="">
                                </div>
                                <div class="program__content">
                                    <span>Agriculture</span>
                                    <h4>Bio engneering</h4>
                                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut</p>
                                    <a href="#" class="boxed-btn5">Apply NOw</a>
                                </div>
                            </div>
                        </div>
                    </div>
            </div>
            <div class="tab-pane fade" id="nav-contact" role="tabpanel" aria-labelledby="nav-contact-tab">
                            <div class="row">
                        <div class="col-lg-4 col-md-6">
                            <div class="single__program">
                                <div class="program_thumb">
                                    <img src="img/program/3.png" alt="">
                                </div>
                                <div class="program__content">
                                    <span>Agriculture</span>
                                    <h4>Chemical engneering</h4>
                                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut</p>
                                    <a href="#" class="boxed-btn5">Apply NOw</a>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-4 col-md-6">
                            <div class="single__program">
                                <div class="program_thumb">
                                    <img src="img/program/2.png" alt="">
                                </div>
                                <div class="program__content">
                                    <span>Agriculture</span>
                                    <h4>Mechanical engneering</h4>
                                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut</p>
                                    <a href="#" class="boxed-btn5">Apply NOw</a>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-4 col-md-6">
                            <div class="single__program">
                                <div class="program_thumb">
                                    <img src="img/program/1.png" alt="">
                                </div>
                                <div class="program__content">
                                    <span>Agriculture</span>
                                    <h4>Bio engneering</h4>
                                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut</p>
                                    <a href="#" class="boxed-btn5">Apply NOw</a>
                                </div>
                            </div>
                        </div>
                    </div>
            </div>
            <div class="tab-pane fade" id="nav-contact2" role="tabpanel" aria-labelledby="nav-contact-tab">
                            <div class="row">
                        <div class="col-lg-4 col-md-6">
                            <div class="single__program">
                                <div class="program_thumb">
                                    <img src="img/program/2.png" alt="">
                                </div>
                                <div class="program__content">
                                    <span>Agriculture</span>
                                    <h4>Chemical engneering</h4>
                                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut</p>
                                    <a href="#" class="boxed-btn5">Apply NOw</a>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-4 col-md-6">
                            <div class="single__program">
                                <div class="program_thumb">
                                    <img src="img/program/1.png" alt="">
                                </div>
                                <div class="program__content">
                                    <span>Agriculture</span>
                                    <h4>Mechanical engneering</h4>
                                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut</p>
                                    <a href="#" class="boxed-btn5">Apply NOw</a>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-4 col-md-6">
                            <div class="single__program">
                                <div class="program_thumb">
                                    <img src="img/program/3.png" alt="">
                                </div>
                                <div class="program__content">
                                    <span>Agriculture</span>
                                    <h4>Bio engneering</h4>
                                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut</p>
                                    <a href="#" class="boxed-btn5">Apply NOw</a>
                                </div>
                            </div>
                        </div>
                    </div>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-12">
                <div class="course_all_btn text-center">
                    <a href="Courses.html" class="boxed-btn4">View All course</a>
                </div>
            </div>
        </div>
    </div>
</div>

templates/snippets/recent_post.html
<aside class="single_sidebar_widget popular_post_widget">
    <h3 class="widget_title">Recent Post</h3>

    {% for post in object_list %}
    <div class="media post_item">
       
       {% if post.image %}
       <img src="{{ post.image.url }}" alt="post" style="width: 40px;">
       {% endif %}

       <div class="media-body">
          <a href="{% url 'blog:detail' post.slug %}">
             <h3>{{ post.title|truncatewords:5 }}</h3>
          </a>
          <p>{{ post.timestamp|date:"F d, Y" }}</p>
       </div>
    </div>
    {% if forloop.counter == 5 %}
       <div style="display: none;">
          {% endif %}
          {% endfor %}
       </div>
 </aside>

templates/snippets/service_area.html
<div class="service_area gray_bg">
    <div class="container">
        <div class="row justify-content-center ">
            <div class="col-lg-4 col-md-6">
                <div class="single_service d-flex align-items-center ">
                    <div class="icon">
                        <i class="flaticon-school"></i>
                    </div>
                    <div class="service_info">
                        <h4>Scholarship</h4>
                        <p>Available</p>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 col-md-6">
                <div class="single_service d-flex align-items-center ">
                    <div class="icon">
                        <i class="flaticon-error"></i>
                    </div>
                    <div class="service_info">
                        <h4>Scholarship</h4>
                        <p>Available</p>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 col-md-6">
                <div class="single_service d-flex align-items-center ">
                    <div class="icon">
                        <i class="flaticon-book"></i>
                    </div>
                    <div class="service_info">
                        <h4>Scholarship</h4>
                        <p>Available</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>