blog/urls.py
from django.contrib.auth.decorators import login_required, permission_required
from django.urls import path
from .views import (
    BlogPostHomeView,
    BlogPostDetailView,
    BlogPostCreateView,
    BlogPostUpdateView,
    BlogPostDeleteView,
    CategoryView,
    LikeView,
    CommentDeleteView,
    CommentEditView,
)

app_name = 'blog'

urlpatterns = [
    path('', BlogPostHomeView.as_view(), name='blogs'),
    path('create/', login_required(BlogPostCreateView.as_view()), name='create'),
    path('edit/<slug>/', login_required(BlogPostUpdateView.as_view()), name='update'),
    path('delete/<slug>/', login_required(BlogPostDeleteView.as_view()), name='delete'),
    path('<slug>/', BlogPostDetailView.as_view(), name='detail'),
    path('categories/<cat>/', CategoryView, name='category'),
    path('like/<slug>/', LikeView, name='like-post'),
    path('delete/comment/<int:pk>/', login_required(CommentDeleteView.as_view()), name='delete-comment'),
    path('edit/comment/<int:pk>/', login_required(CommentEditView.as_view()), name='edit-comment'),
]

main/urls.py
from django.contrib.auth.decorators import login_required, permission_required
from django.urls import path
from .views import (
    HomeView,
    ShowProfilePageView,
    EditProfilePageView,
)

app_name = 'main'

urlpatterns = [
    path('', HomeView.as_view(), name='index'),
    path('<slug>/accounts/profile/', ShowProfilePageView.as_view(), name='user-profile'),
    path('<slug>/accounts/edit/profile/', login_required(EditProfilePageView.as_view()), name='edit-profile'),
]

oduduwa/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('posts/', include('blog.urls', namespace='blog')),
    path('accounts/', include('allauth.urls')),
    path('search/', include("searches.urls", namespace='searches')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blog/models.py
from django.db import models
from django.conf import settings
from django.db.models import Q
from django.utils import timezone
from django.shortcuts import reverse
from datetime import datetime, date
from ckeditor.fields import RichTextField
from django.db.models.signals import pre_save, post_save
from oduduwa.utils import unique_slug_generator, unique_slug_generator_for_user
from django.contrib.auth.models import User


CATEGORY_CHOICES = [
    ('announcement', 'Announcement'),
    ('school news', 'School News')
    ]


CLASS_NAME_CHOICES = [
    ('JSS1', 'JSS1'),
    ('JSS2', 'JSS2'),
    ('JSS3', 'JSS3'),
    ('SSS1', 'SSS1'),
    ('SSS2', 'SSS2'),
    ('SSS3', 'SSS3'),
    ('Other Class', 'Other Class'),
    ]

ROLE_CHOICES = [
    ('Student', 'Student'),
    ('Old Student', 'Old Student'),
    ('Teacher', 'Teacher'),
    ('Principal', 'Principal'),
    ('Vice-Principal', 'Vice-Principal'),
    ('Non-Member', 'Non-Member'),
    ]

# class Category(models.Model):
#     name = models.CharField(max_length=225)
    
#     def __str__(self):
#         return self.name

#     def get_absolute_url(self):
#         return "/"

# NOTE Do this later

class BlogPostQuerySet(models.query.QuerySet):
    def search(self, query):
        lookups = (
            Q(title__icontains=query) |
            Q(timestamp__icontains=query) |
            Q(category__icontains=query)
        )
        return self.filter(lookups).distinct()


class BlogPostManager(models.Manager):
    def get_queryset(self):
        return BlogPostQuerySet(self.model, using=self._db)

    def search(self, query=None):
        return self.get_queryset().search(query)


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    slug = models.SlugField(max_length=500, null=True, blank=True)
    bio = models.TextField(null=True, blank=True)
    profile_pic = models.ImageField(null=True, blank=True, upload_to="profile-images/")
    class_name = models.CharField(choices=CLASS_NAME_CHOICES, max_length=225, null=True, blank=True)
    role = models.CharField(choices=ROLE_CHOICES, max_length=225, null=True, blank=True)

    def __str__(self):
        return str(self.user)


def create_profile(sender, **kwargs):
    if kwargs['created']:
        user_profile = UserProfile.objects.create(user=kwargs['instance'])

post_save.connect(create_profile, sender=User)


def slug_generator_for_user(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = unique_slug_generator_for_user(instance)

pre_save.connect(slug_generator_for_user, sender=UserProfile)


class BlogPost(models.Model):
    title = models.CharField(max_length=225)
    image = models.ImageField(null=True, blank=True, upload_to="blog-images/")
    slug = models.SlugField(max_length=500, null=True, blank=True)
    # content = models.TextField(null=True, blank=True)
    content = RichTextField()
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now_add=True)
    category = models.CharField(choices=CATEGORY_CHOICES, max_length=225)
    likes = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='blog_posts_likes')
    # image = models.ImageField(upload_to='image/', blank=True, null=True)
    # slug = models.SlugField(unique=True)
    # publish_date = models.DateTimeField(auto_now=False, auto_now_add=False, null=True, blank=True)
    # updated = models.DateTimeField(auto_now=True)
    
    objects = BlogPostManager()
    
    class Meta:
        ordering = ['-timestamp']
    
    def __str__(self):
        return f'{self.title} BY == {self.user}'
    
    def total_likes(self):
        return self.likes.count()

    def get_absolute_url(self):
        return f"/posts/{self.id}"
        # return reverse("blog:detail", args=(str(self.id)))

    def search(self, query=None):
        if query is None:
            return self.objects.none()
        return self.objects.search()


def slug_generator(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = unique_slug_generator(instance)


pre_save.connect(slug_generator, sender=BlogPost)


class Comment(models.Model):
    blog_post = models.ForeignKey(BlogPost, related_name="comments", on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    body = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        ordering = ['-timestamp']

    def __str__(self):
        return f'{self.blog_post.title} == {self.user}'

blog/forms.py
from django import forms
from .models import BlogPost, Comment


class BlogPostForm(forms.ModelForm):
    
    class Meta:
        model = BlogPost
        fields = ("title", 'category', 'image', 'content')
        widgets = {
            'title' : forms.TextInput(attrs={'class': 'form-control'}),
            'category' : forms.Select(attrs={'class': 'form-control'}),
            'content' : forms.Textarea(attrs={'class': 'form-control md-textarea rounded-0'})
        }

class UpdateBlogPostForm(forms.ModelForm):
    
    class Meta:
        model = BlogPost
        fields = ("title", 'category', 'image', 'content')
        widgets = {
            'title' : forms.TextInput(attrs={'class': 'form-control'}),
            'category' : forms.Select(attrs={'class': 'form-control'}),
            'content' : forms.Textarea(attrs={'class': 'form-control md-textarea rounded-0'})
        }

class BlogPostCommentForm(forms.ModelForm):
    
    class Meta:
        model = Comment
        fields = ("body",)
        widgets = {
            'body' : forms.Textarea(attrs={
                'class': 'form-control w-100',
                'id': "comment",
                'cols': '30',
                'rows': '9',
                'placeholder': 'Write Comment',
                })
        }

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect, get_list_or_404
from django.contrib import messages
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView, RedirectView
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core.exceptions import ObjectDoesNotExist, MultipleObjectsReturned
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.detail import SingleObjectMixin
from django.urls import reverse, reverse_lazy
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.http import HttpResponseRedirect
from .models import BlogPost, Comment
from .forms import BlogPostForm, UpdateBlogPostForm, BlogPostCommentForm

# Create your views here.

@login_required
def LikeView(request, slug):
    post = get_object_or_404(BlogPost, slug=request.POST.get('post_id'))
    liked = False
    if post.likes.filter(id=request.user.id).exists():
        post.likes.remove(request.user)
        liked = False
    else:
        post.likes.add(request.user)
        liked = True
    return HttpResponseRedirect(reverse('blog:detail', args=[slug] ))


class BlogPostHomeView(ListView):
    model = BlogPost
    # context_object_name = 
    template_name='blog.html'
    paginate_by = 10
    

class BlogPostCreateView(CreateView):
    model = BlogPost
    form_class = BlogPostForm
    template_name = "create_post.html"
    # fields = '__all__'
    # fields = ('title', 'content')

    def get_form_kwargs(self):
        kwargs = super(BlogPostCreateView, self).get_form_kwargs()
        if kwargs['instance'] is None:
            kwargs['instance'] = BlogPost()
        kwargs['instance'].user = self.request.user
        return kwargs
    
    def get_success_url(self):
        # Assuming there is a ForeignKey from Comment to Post in your model
        post = self.object
        return reverse_lazy('blog:detail', kwargs={'slug': post.slug})


class BlogPostUpdateView(UpdateView):
    model = BlogPost
    form_class = UpdateBlogPostForm
    template_name = "update_post.html"
    # fields = ['title', 'content']
    
    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super(BlogPostUpdateView, self).post(request, *args, **kwargs)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['user'] = self.object.user
        return context
    
    def get_success_url(self):
        # Assuming there is a ForeignKey from Comment to Post in your model
        post = self.object
        return reverse_lazy('blog:detail', kwargs={'slug': post.slug})


class BlogPostDeleteView(DeleteView):
    model = BlogPost
    template_name = "delete_post.html"
    success_url = reverse_lazy('blog:blogs')
    
    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super(BlogPostDeleteView, self).post(request, *args, **kwargs)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['user'] = self.object.user
        return context


class BlogPostDetailView(DetailView):
    model = BlogPost
    template_name='single-blog.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        
        get_post = get_object_or_404(BlogPost, slug=self.kwargs['slug'])
        total_likes = get_post.total_likes()
        
        liked = False
        
        if get_post.likes.filter(id=self.request.user.id).exists():
            liked = True
        
        context['total_likes'] = total_likes
        context['liked'] = liked
        
        context['object_list'] = BlogPost.objects.all()
        
        context['comments'] = Comment.objects.filter(blog_post_id=self.object.id).all()
        context['form'] = BlogPostCommentForm
        return context
    
    def post(self, request, slug):
       post = get_object_or_404(BlogPost, slug=slug)
       form = BlogPostCommentForm(request.POST)

       if form.is_valid():
           obj  = form.save(commit=False)
           obj.blog_post = post
           obj.user = self.request.user
           obj.save()
           return redirect('blog:detail', post.slug)


class CommentDeleteView(DeleteView):
    model = Comment
    template_name = "delete_comment.html"
    
    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super(CommentDeleteView, self).post(request, *args, **kwargs)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['user'] = self.object.user
        return context
    
    def get_success_url(self):
        # Assuming there is a ForeignKey from Comment to Post in your model
        post = self.object.blog_post
        return reverse_lazy('blog:detail', kwargs={'slug': post.slug})


class CommentEditView(UpdateView):
    model = Comment
    form_class = BlogPostCommentForm
    template_name = "edit_comment.html"
    
    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super(CommentEditView, self).post(request, *args, **kwargs)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['user'] = self.object.user
        return context
    
    def get_success_url(self):
        # Assuming there is a ForeignKey from Comment to Post in your model
        post = self.object.blog_post
        return reverse_lazy('blog:detail', kwargs={'slug': post.slug})

# NOTE THIS IS JUST IF I WANTED TO CREATE THE COMMENT IN OTHER PAGE(AND OTHER STUFFS)
# class CommentCreateView(CreateView):
#     model = Comment
#     form_class = BlogPostCommentForm
    
#     def form_valid(self, form):
#         form.instance.blog_post_id = self.kwargs['pk']
#         return super().form_valid(form)
    
#     def get_context_data(self, **kwargs):
#         context = super(CommentCreate, self).get_context_data(**kwargs)
#         context['post'] = get_object_or_404(Post, pk = self.kwargs['pk'])
#         return context

#     def form_valid(self, form):
#         form.instance.author = self.request.user
#         form.instance.post=get_object_or_404(Post, pk = self.kwargs['pk'])
#         return super(CommentCreate, self).form_valid(form)

#     def get_success_url(self):
#         return reverse('post-detail', kwargs={'pk': self.kwargs['pk'],})


def CategoryView(request, cat):
    category_posts = BlogPost.objects.filter(category=cat.replace('-', ' '))
    object_list = BlogPost.objects.all()
    if category_posts:
        for categories in category_posts:
            category = categories
    else:
        category = None
    paginator = Paginator(category_posts, 10)
    
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    
    context = {
        'page_obj': page_obj,
        'object_list': object_list,
        'category':category,
        'category_name':cat.replace('-', ' '),
        'category_posts':category_posts
    }
    return render(request, 'category.html', context)

templates/create_post.html
{% extends 'base.html' %}

{% load static %}

{% block head_title %} Create A New Post {% endblock %}

{% block extra_head %}
{% endblock %}

{% block content %}

<div class="text-center mt-4">
    <h3>Create A New Post</h3>
</div>

<div class="card-body px-lg-5 pt-0">
    <div class="form-group">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.media }}
            {{ form.as_p }}
            <div class="text-center">
                <button type="submit" class="btn btn-lg btn-outline-dark waves-effect">Post</button>
            </div>
        </form>
    </div>
</div>

{% endblock %}

{% block extra_script %}
  
{% endblock extra_script %}

templates/delete_comment.html
{% extends 'base.html' %}

{% load static %}

{% block head_title %} Delete Your Comment {% endblock %}

{% block extra_head %}
{% endblock %}

{% block content %}

{% if request.user.id == user.id %}
<div class="container text-center">
    <h3 class="mt-4">Delete Your Comment</h3>

    <div class="form-group">
        <form method="post" class="border border-light p-5">
            {% csrf_token %}
            <button type="submit" class="btn btn-lg btn-outline-danger waves-effect">Delete Comment</button>
            <div style="padding-bottom: 106px;"></div>
        </form>
    </div>
</div>
{% else %}
    <div class="text-center mt-5 mb-5">
        <h1>You're not allowed here!</h1>
    </div>
{% endif %}

{% endblock %}

{% block extra_script %}
  
{% endblock extra_script %}

templates/edit_comment.html
{% extends 'base.html' %}

{% load static %}

{% block head_title %} Edit Your Comment {% endblock %}

{% block extra_head %}
{% endblock %}

{% block content %}

{% if request.user.id == user.id %}
    <div class="text-center mt-4">
        <h3>Edit Your Comment</h3>
    </div>

<div class="card-body px-lg-5 pt-0">
    <div class="form-group">
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <div class="text-center">
                <button type="submit" class="btn btn-lg btn-outline-danger waves-effect">Update</button>
            </div>
        </form>
    </div>
</div>

{% else %}
    <div class="text-center mt-5 mb-5">
        <h1>You're not allowed here!</h1>
    </div>
{% endif %}

{% endblock %}

{% block extra_script %}
  
{% endblock extra_script %}

templates/single-blog.html
{% extends 'base.html' %}

{% load static %}

{% block head_title %} {{ object.title }} {% endblock %}

{% block extra_head %}
{% endblock %}

{% block content %}
  <!-- bradcam_area_start  -->
  <div class="bradcam_area breadcam_bg">
      <div class="container">
          <div class="row">
              <div class="col-xl-12">
                  <div class="bradcam_text">
                      <h3>Single Blog</h3>
                  </div>
              </div>
          </div>
      </div>
  </div>
  <!-- bradcam_area_end  -->

   <!--================Blog Area =================-->
   <section class="blog_area single-post-area section-padding">
      <div class="container">
         <div class="row">
            <div class="col-lg-8 posts-list">
               <div class="single-post">
                  {% if object.image %}
                  <div class="feature-img">
                     <img class="img-fluid" src="{{ object.image.url }}" alt="" style="width: 80%;">
                  </div>
                  {% endif %}
                  <div class="blog_details">
                     <h2>{{ object.title }}</h2>
                     <ul class="blog-info-link mt-3 mb-4">
                        <li><a href="{% url 'blog:category' object.category|slugify %}" style="text-transform: capitalize;"><i class="fa fa-user"></i> {{ object.category }}</a></li>
                        
                        {% if comments %}
                        <li><a href="#comment"><i class="fa fa-comments"></i> {{ comments.count }} Comment{{ comments|pluralize }}</a></li>
                        {% else %}
                        <li><i class="fa fa-comments"></i> 0 Comment</li>
                        {% endif %}
                           
                        {% if request.user.id == object.user.id %}
                           <li><a href="{% url 'blog:update' object.slug %}">Edit</a></li>
                           <li><a href="{% url 'blog:delete' object.slug %}">Delete</a></li>
                        {% endif %}
                     </ul>
                     <p class="excert">
                        {{ object.content|safe|linebreaks }}
                     </p>
                  </div>
               </div>
               <div id="like"></div>
               <div class="navigation-top">
                  <div class="d-sm-flex justify-content-between text-center">
                     <p class="like-info">
                        <span class="align-middle">
                           {% if user.is_authenticated %}
                              <form action="{% url 'blog:like-post' object.slug %}#like" method="POST">
                                 {% csrf_token %}
                                 {% if liked %}
                                    <button name="post_id" value="{{ object.slug }}" style="background: none; border: none;">
                                       <i class="fas fa-heart" style="cursor: pointer;"></i>
                                       {% if total_likes == 1 %}
                                       Liked by you
                                       {% elif total_likes == 2 %}
                                       Liked by you and {{ total_likes|add:"-1" }} other
                                       {% else %}
                                       Liked by you and {{ total_likes|add:"-1" }} others
                                       {% endif %}
                                    </button>
                                 {% else %}
                                    <button name="post_id" value="{{ object.slug }}" style="background: none; border: none;">
                                       <i class="far fa-heart" style="cursor: pointer;"></i>
                                    </button>
                                    {% if total_likes == 0 %}
                                       {{ total_likes }} Like
                                    {% else %}
                                       {{ total_likes }} Like{{ total_likes|pluralize }}
                                    {% endif %}
                                 {% endif %}
                                    
                              </form>
                           {% else %}
                              <i class="fa fa-heart"></i>
                              {% if total_likes == 0 %}
                              0 Likes
                              {% elif total_likes == 1 %}
                              Liked by 1 person
                              {% else %}
                              Liked by {{ total_likes }} people
                              {% endif %}
                           {% endif %}
                        </span>
                     </p>
                     <div class="col-sm-4 text-center my-2 my-sm-0">
                        <!-- <p class="comment-count"><span class="align-middle"><i class="fa fa-comment"></i></span> 06 Comments</p> -->
                     </div>
                  </div>

                  <div class="navigation-area">
                     <div class="row">
                        {% if object.get_previous_by_timestamp %}
                        <div
                           class="col-lg-6 col-md-6 col-12 nav-left flex-row d-flex justify-content-start align-items-center">
                           {% if object.get_previous_by_timestamp.image %}
                           <div class="thumb">
                              <a href="{% url 'blog:detail' object.get_previous_by_timestamp.slug %}">
                                 <img class="img-fluid" src="{{ object.get_previous_by_timestamp.image.url }}" alt="" style="width: 100px;">
                              </a>
                           </div>
                           {% endif %}
                           <div class="arrow">
                              <a href="{% url 'blog:detail' object.get_previous_by_timestamp.slug %}">
                                 <span class="lnr text-white ti-arrow-left"></span>
                              </a>
                           </div>
                           <div class="detials">
                              <p>Prev Post</p>
                              <a href="{% url 'blog:detail' object.get_previous_by_timestamp.slug %}">
                                 <h4>{{ object.get_previous_by_timestamp.title|truncatewords:3 }}</h4>
                              </a>
                           </div>
                        </div>
                        {% endif %}

                        {% if object.get_next_by_timestamp %}
                        <div
                           class="col-lg-6 col-md-6 col-12 nav-right flex-row d-flex justify-content-end align-items-center">
                           <div class="detials">
                              <p>Next Post</p>
                              <a href="{% url 'blog:detail' object.get_next_by_timestamp.slug %}">
                                 <h4>{{ object.get_next_by_timestamp.title|truncatewords:3 }}</h4>
                              </a>
                           </div>
                           <div class="arrow">
                              <a href="{% url 'blog:detail' object.get_next_by_timestamp.slug %}">
                                 <span class="lnr text-white ti-arrow-right"></span>
                              </a>
                           </div>
                           {% if object.get_next_by_timestamp.image %}
                           <div class="thumb">
                              <a href="{% url 'blog:detail' object.get_next_by_timestamp.slug %}">
                                 <img class="img-fluid" src="{{ object.get_next_by_timestamp.image.url }}" alt="" style="width: 100px;">
                              </a>
                           </div>
                          {% endif %}
                        </div>
                        {% endif %}
                     </div>
                  </div>
               </div>
               <div class="blog-author">
                  <div class="media align-items-center">
                     <a href="{% url 'main:user-profile' object.user.userprofile.slug %}">
                     
                     {% if object.user.userprofile.profile_pic %}
                        <img src="{{ object.user.userprofile.profile_pic.url }}" alt="">
                     {% else %}
                        <img src="{% static 'odu-prod/img/profile/default-profile.jpg' %}" alt="">
                     {% endif %}
                     
                     <div class="media-body">
                           <h4>{{ object.user.userprofile.user }}</h4>
                        </a>
                        
                        {% if object.user.userprofile.bio %}
                        <p>{{ object.user.userprofile.bio|truncatewords:25 }}</p>
                        {% endif %}
                        
                     <p>
                        {% if object.user.userprofile.role %}
                        {{ object.user.userprofile.role }}
                        <span class="ml-2"></span>
                        {% endif %}

                        {% if object.user.userprofile.class_name %}
                        {{ object.user.userprofile.class_name }}
                        {% endif %}
                     </p>

                     </div> 
                  </div>
               </div>

               {% if comments %}
               <div class="comments-area" id="comment">
                  <h4>
                     {{ comments.count }} Comment{{ comments|pluralize }}</a></li>
                  </h4>
                  {% for comment in comments %}
                  <div class="comment-list">
                     <div class="single-comment justify-content-between d-flex">
                        <div class="user justify-content-between d-flex">
                           <div class="thumb">
                              <a href="{% url 'main:user-profile' comment.user.userprofile.slug %}">
                                 {% if comment.user.userprofile.profile_pic %}
                                    <img src="{{ comment.user.userprofile.profile_pic.url }}" alt="">
                                 {% else %}
                                    <img src="{% static 'odu-prod/img/profile/default-profile.jpg' %}" alt="">
                                 {% endif %}
                              </a>
                           </div>
                           <div class="desc">
                              <p class="comment">
                                 {{ comment.body }}
                              </p>
                              <div class="d-flex justify-content-between">
                                 <div class="d-flex align-items-center">
                                    <h5>
                                       <a href="{% url 'main:user-profile' comment.user.userprofile.slug %}">{{ comment.user }}</a>
                                    </h5>
                                    <p class="date">{{ comment.timestamp|date:"F d, Y" }} at {{ comment.timestamp|date:"P" }} </p>
                                 </div>
                                 <div class="reply-btn">
                                    {% if request.user.id == comment.user.id %}
                                       <a class="btn-reply text-uppercase" href="{% url 'blog:edit-comment' comment.id %}">Edit</a>
                                       <a class="btn-reply text-uppercase" href="{% url 'blog:delete-comment' comment.id %}">Delete</a>
                                    {% endif %}
                                 </div>
                              </div>
                           </div>
                        </div>
                     </div>
                  </div>
                  {% endfor %}
               </div>
               {% endif %}
               
               {% if user.is_authenticated %}
                  
               <div class="comment-form">
                  <h4>Leave a Comment</h4>
                  <form class="form-contact comment_form" method="POST">
                     {% csrf_token %}
                     <div class="row">
                        <div class="col-12">
                           <div class="form-group">
                              {{ form.as_p }}
                           </div>
                        </div>
                     </div>
                     <div class="form-group">
                        <button type="submit" class="button button-contactForm btn_1 boxed-btn">Post</button>
                     </div>
                  </form>
               </div>

               {% endif %}
               
            </div>
            <div class="col-lg-4">
               <div class="blog_right_sidebar">

                  {% include "snippets/category.html" %}
                  {% include "snippets/recent_post.html" %}

               </div>
            </div>
         </div>
      </div>
   </section>
   <!--================ Blog Area end =================-->
{% endblock %}

{% block extra_script %}
   <script>
      $('#datepicker').datepicker({
          iconsLibrary: 'fontawesome',
          icons: {
           rightIcon: '<span class="fa fa-caret-down"></span>'
       }
      });
      $('#datepicker2').datepicker({
          iconsLibrary: 'fontawesome',
          icons: {
           rightIcon: '<span class="fa fa-caret-down"></span>'
       }

      });
  </script>
{% endblock extra_script %}